import gzip
import os

import pytest

from prosig.sequences import (
    indexed_fasta_sequence,
    write_swissprot_sequence_artifacts,
)


def test_write_swissprot_sequence_artifacts_and_indexed_lookup(tmp_path) -> None:
    swissprot = tmp_path / "uniprot_sprot.dat.gz"
    fasta = tmp_path / "accession.fasta"
    index = tmp_path / "accession.fasta.idx"
    with gzip.open(swissprot, "wt", encoding="utf-8") as handle:
        handle.write(
            "ID   FIRST\n"
            "AC   P00001; Q00001;\n"
            "SQ   SEQUENCE   8 AA;\n"
            "     MABC DEFG\n"
            "//\n"
            "ID   SECOND\n"
            "AC   P00002;\n"
            "SQ   SEQUENCE   4 AA;\n"
            "     WXYZ\n"
            "//\n"
        )

    result = write_swissprot_sequence_artifacts(swissprot, fasta, index)

    assert result.sequences == 2
    assert result.residues == 12
    assert fasta.read_text(encoding="ascii") == (
        ">P00001\nMABCDEFG\n>P00002\nWXYZ\n"
    )
    assert "Generated by ProSig; do not edit" in index.read_text(encoding="ascii")
    assert indexed_fasta_sequence("P00001", fasta, index) == "MABCDEFG"
    assert indexed_fasta_sequence("Q00001", fasta, index) is None
    assert indexed_fasta_sequence("MISSING", fasta, index) is None


def test_indexed_fasta_sequence_rejects_modified_fasta(tmp_path) -> None:
    swissprot = tmp_path / "uniprot_sprot.dat.gz"
    fasta = tmp_path / "accession.fasta"
    index = tmp_path / "accession.fasta.idx"
    with gzip.open(swissprot, "wt", encoding="utf-8") as handle:
        handle.write(
            "ID   FIRST\n"
            "AC   P00001;\n"
            "SQ   SEQUENCE   4 AA;\n"
            "     ABCD\n"
            "//\n"
        )
    write_swissprot_sequence_artifacts(swissprot, fasta, index)
    original_stat = fasta.stat()
    fasta.write_text(">P00001\nWXYZ\n", encoding="ascii")
    changed_mtime = original_stat.st_mtime_ns + 1_000_000
    os.utime(fasta, ns=(changed_mtime, changed_mtime))

    with pytest.raises(ValueError, match="FASTA changed"):
        indexed_fasta_sequence("P00001", fasta, index)
