"""Swiss-Prot sequence artifact generation and indexed lookup."""

from __future__ import annotations

import gzip
import os
import stat
import tempfile
from dataclasses import dataclass
from functools import cache
from pathlib import Path

FASTA_INDEX_VERSION = "1"


@dataclass(frozen=True)
class SequenceArtifactResult:
    """Summary of generated sequence artifacts."""

    fasta_file: Path
    index_file: Path
    sequences: int
    residues: int


def write_swissprot_sequence_artifacts(
    swissprot: str | Path,
    fasta_file: str | Path,
    index_file: str | Path,
) -> SequenceArtifactResult:
    """Write primary-accession FASTA and byte-offset index artifacts."""
    source = Path(swissprot)
    fasta_path = Path(fasta_file)
    index_path = Path(index_file)
    fasta_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.parent.mkdir(parents=True, exist_ok=True)

    fasta_temp = _temporary_path(fasta_path)
    index_temp = _temporary_path(index_path)
    sequence_count = 0
    residue_count = 0

    try:
        with (
            gzip.open(
                source,
                "rt",
                encoding="utf-8",
                errors="replace",
            ) as source_handle,
            fasta_temp.open("wb") as fasta_handle,
            index_temp.open("w+b") as index_handle,
        ):
            index_handle.write(
                b"# Generated by ProSig; do not edit the FASTA without rebuilding "
                b"this index.\n"
            )
            index_handle.write(f"# version\t{FASTA_INDEX_VERSION}\n".encode("ascii"))
            index_handle.write(f"# fasta_name\t{fasta_path.name}\n".encode("ascii"))
            index_handle.write(b"# fasta_size\t")
            fasta_size_position = index_handle.tell()
            index_handle.write(b"00000000000000000000\n")
            index_handle.write(b"# fasta_mtime_ns\t")
            fasta_mtime_position = index_handle.tell()
            index_handle.write(b"00000000000000000000\n")
            index_handle.write(b"accession\toffset\tlength\n")

            primary_accession: str | None = None
            sequence_parts: list[str] = []
            reading_sequence = False

            for raw_line in source_handle:
                line = raw_line.rstrip("\n")
                if line == "//":
                    if primary_accession is not None and sequence_parts:
                        sequence = "".join(sequence_parts).encode("ascii")
                        fasta_handle.write(f">{primary_accession}\n".encode("ascii"))
                        sequence_offset = fasta_handle.tell()
                        fasta_handle.write(sequence)
                        fasta_handle.write(b"\n")
                        index_handle.write(
                            (
                                f"{primary_accession}\t{sequence_offset}\t"
                                f"{len(sequence)}\n"
                            ).encode("ascii")
                        )
                        sequence_count += 1
                        residue_count += len(sequence)
                    primary_accession = None
                    sequence_parts = []
                    reading_sequence = False
                    continue

                if line.startswith("AC") and primary_accession is None:
                    accessions = [
                        accession.strip()
                        for accession in line[5:].split(";")
                        if accession.strip()
                    ]
                    if accessions:
                        primary_accession = accessions[0]
                    continue

                if line.startswith("SQ"):
                    reading_sequence = True
                    continue

                if reading_sequence:
                    sequence_parts.append("".join(line.split()))

            if primary_accession is not None and sequence_parts:
                sequence = "".join(sequence_parts).encode("ascii")
                fasta_handle.write(f">{primary_accession}\n".encode("ascii"))
                sequence_offset = fasta_handle.tell()
                fasta_handle.write(sequence)
                fasta_handle.write(b"\n")
                index_handle.write(
                    (
                        f"{primary_accession}\t{sequence_offset}\t"
                        f"{len(sequence)}\n"
                    ).encode("ascii")
                )
                sequence_count += 1
                residue_count += len(sequence)

            fasta_handle.flush()
            fasta_stat = fasta_temp.stat()
            index_handle.seek(fasta_size_position)
            index_handle.write(f"{fasta_stat.st_size:020d}".encode("ascii"))
            index_handle.seek(fasta_mtime_position)
            index_handle.write(f"{fasta_stat.st_mtime_ns:020d}".encode("ascii"))

        fasta_temp.chmod(_output_mode(fasta_path))
        index_temp.chmod(_output_mode(index_path))
        os.replace(fasta_temp, fasta_path)
        os.replace(index_temp, index_path)
    finally:
        fasta_temp.unlink(missing_ok=True)
        index_temp.unlink(missing_ok=True)

    return SequenceArtifactResult(
        fasta_file=fasta_path,
        index_file=index_path,
        sequences=sequence_count,
        residues=residue_count,
    )


def indexed_fasta_sequence(
    accession: str,
    fasta_file: str | Path = "accession.fasta",
    index_file: str | Path = "accession.fasta.idx",
) -> str | None:
    """Return one sequence through the FASTA byte-offset index, or None."""
    fasta_path = Path(fasta_file)
    index_path = Path(index_file)
    fasta_stat = fasta_path.stat()
    index = _load_fasta_index(
        str(index_path.resolve()),
        str(fasta_path.resolve()),
        fasta_stat.st_size,
        fasta_stat.st_mtime_ns,
    )
    location = index.get(accession.strip())
    if location is None:
        return None
    offset, length = location
    with fasta_path.open("rb") as handle:
        handle.seek(offset)
        sequence = handle.read(length)
    return sequence.decode("ascii")


@cache
def _load_fasta_index(
    index_file: str,
    fasta_file: str,
    fasta_size: int,
    fasta_mtime_ns: int,
) -> dict[str, tuple[int, int]]:
    metadata: dict[str, str] = {}
    entries: dict[str, tuple[int, int]] = {}
    with Path(index_file).open("r", encoding="ascii") as handle:
        for raw_line in handle:
            line = raw_line.rstrip("\n")
            if not line:
                continue
            if line.startswith("# "):
                key_value = line[2:].split("\t", 1)
                if len(key_value) == 2:
                    metadata[key_value[0]] = key_value[1]
                continue
            if line == "accession\toffset\tlength":
                continue
            accession, offset, length = line.split("\t")
            entries[accession] = (int(offset), int(length))

    if metadata.get("version") != FASTA_INDEX_VERSION:
        raise ValueError(f"Unsupported FASTA index version: {index_file}")
    if metadata.get("fasta_name") != Path(fasta_file).name:
        raise ValueError(f"FASTA index does not match FASTA file: {index_file}")
    if _metadata_integer(metadata, "fasta_size", index_file) != fasta_size:
        raise ValueError(f"FASTA changed after its index was generated: {fasta_file}")
    if _metadata_integer(metadata, "fasta_mtime_ns", index_file) != fasta_mtime_ns:
        raise ValueError(f"FASTA changed after its index was generated: {fasta_file}")
    return entries


def _metadata_integer(
    metadata: dict[str, str],
    key: str,
    index_file: str,
) -> int:
    try:
        return int(metadata[key])
    except (KeyError, ValueError) as exc:
        raise ValueError(
            f"Invalid FASTA index metadata in {index_file}: {key}"
        ) from exc


def _temporary_path(destination: Path) -> Path:
    descriptor, name = tempfile.mkstemp(
        prefix=f".{destination.name}.",
        suffix=".tmp",
        dir=destination.parent,
    )
    os.close(descriptor)
    return Path(name)


def _output_mode(destination: Path) -> int:
    if destination.exists():
        return stat.S_IMODE(destination.stat().st_mode)
    current_umask = os.umask(0)
    os.umask(current_umask)
    return 0o666 & ~current_umask
